sudo: true

# Do not choose a language; we provide our own build tools.
language: generic

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

matrix:
  include:
  # Build on linux
  - compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  # Build on macOS in addition to Linux
  # (for now MacOS is unsupported: issue with static linking)
  - compiler: ": #stack default osx"
    os: osx

before_install:
# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
  if [ -n "$CACHE_S3_VERSION" ]; then
    travis_retry curl -f -L https://github.com/fpco/cache-s3/releases/download/$CACHE_S3_VERSION/cache-s3-CACHE_S3_VERSION-$TRAVIS_OS_NAME-x86_64.tar.gz | tar xz -C ~/.local/bin 'cache-s3'
    if [ ! $? = 0 ]; then
      cache-s3 --prefix=$TRAVIS_REPO_SLUG \
               --git-branch="$TRAVIS_BRANCH" \
               --suffix="$TRAVIS_OS_NAME" \
               --verbosity=debug \
               restore stack --base-branch=master
      cache-s3 --prefix=$TRAVIS_REPO_SLUG \
               --git-branch="$TRAVIS_BRANCH" \
               --suffix="$TRAVIS_OS_NAME" \
               --verbosity=debug \
               restore stack work --base-branch=master
    fi
  fi

install:
- |
  set -ex
  stack --no-terminal setup --no-reinstall > /dev/null
  set +ex

script:
- |
  set -ex
  # if [ "$TRAVIS_OS_NAME" = "linux" ]; then
  #   # Workaroud for linker issue.
  #   # See: https://www.fpcomplete.com/blog/2016/10/static-compilation-with-stack#crtbegint-swap
  #   cd /usr/lib/gcc/x86_64-linux-gnu/4.8/
  #   sudo rm crtbeginT.o
  #   sudo cp crtbeginS.o crtbeginT.o
  #   cd $TRAVIS_BUILD_DIR
  #   stack --no-terminal install --force-dirty --ghc-options='-optl-static -optl-pthread -fPIC'
  # else
  #   stack --no-terminal install --force-dirty
  # fi
  stack --no-terminal install
  set +ex

after_success:
- | # Do not cache PRs
  if [ "$TRAVIS_PULL_REQUEST" = false ]; then
    if [ "$TRAVIS_BRANCH" = master ]; then
      stack --no-terminal exec -- cache-s3 --prefix=$TRAVIS_REPO_SLUG \
                                            --git-branch="$TRAVIS_BRANCH" \
                                            --suffix="$TRAVIS_OS_NAME" \
                                            --verbosity=debug \
                                            save stack
    fi
    stack --no-terminal exec -- cache-s3 --prefix=$TRAVIS_REPO_SLUG \
                                         --git-branch="$TRAVIS_BRANCH" \
                                         --suffix="$TRAVIS_OS_NAME" \
                                         --verbosity=debug \
                                         save stack work
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry curl -L https://github.com/tfausak/github-release/releases/download/$env:GITHUB_RELEASE_VERSION/github-release-$GITHUB_RELEASE_VERSION-$TRAVIS_OS_NAME.gz | gunzip > github-release
      chmod a+x github-release
      stack exec -- cp $(which cache-s3) .
      tar -czf cache-s3.tar.gz cache-s3
      .\github-release upload --token=$GITHUB_TOKEN --repo=$TRAVIS_REPO_SLUG --file=cache-s3.tar.gz --tag=$TRAVIS_TAG --name=cache-s3-$TRAVIS_TAG-$TRAVIS_OS_NAME-x86_64.tar.gz
    fi
  fi
