sudo: false

# Do not choose a language; we provide our own build tools.
language: generic
matrix:
  include:
  # Build on linux
  - compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  # Build on macOS in addition to Linux
  - compiler: ": #stack default osx"
    os: osx

before_install:
# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    #travis_retry curl --insecure -L https://github.com/lehins/cache-s3/releases/download/latest/cache-s3-latest-osx-x86_64.tar.gz | tar xz --strip-components=1 --include 'cache-s3' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    #travis_retry curl -L https://github.com/lehins/cache-s3/releases/download/latest/cache-s3-latest-linux-x86_64.tar.gz | tar xz --strip-components=1 -C ~/.local/bin 'cache-s3'
  fi
  travis_retry curl -L https://github.com/lehins/cache-s3/releases/download/latest/cache-s3-latest-$TRAVIS_OS_NAME-x86_64.tar.gz | tar xz -C ~/.local/bin 'cache-s3'

install:
- |
  set -ex
  stack --no-terminal setup --no-reinstall > /dev/null
  set +ex

script:
- |
  set -ex
  stack --no-terminal install --ghc-options='-optl-static -optl-pthread -fPIC'
  set +ex

after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      stack exec -- cache-s3 --prefix=cache-s3 \
                             --git-branch="$TRAVIS_BRANCH" \
                             --suffix="$TRAVIS_OS_NAME" \
                             --verbosity=debug \
                             save stack
    fi
    stack exec -- cache-s3 --prefix=cache-s3 \
                           --git-branch="$TRAVIS_BRANCH" \
                           --suffix="$TRAVIS_OS_NAME" \
                           --verbosity=debug
                           save stack work
  fi
