version: 1.0.{build}
image: Visual Studio 2015

build: off

environment:
  global:
    # Avoid long paths on Windows
    STACK_ROOT: 'c:\s'
    STACK_WORK: '.w'
    WORK_DIR: 'c:\w'


before_test:
# Avoid long paths not to reach MAX_PATH of 260 chars
- xcopy /q /s /e /r /k /i /v /h /y C:\projects\cache-s3 "%WORK_DIR%"
- cd "%WORK_DIR%"

# Install stack
- mkdir %APPDATA%\local\bin\
- set PATH=%PATH%;%APPDATA%\local\bin
- ps: Start-FileDownload http://www.stackage.org/stack/windows-x86_64 -FileName stack.zip
- 7z x stack.zip stack.exe
- cp stack.exe %APPDATA%\local\bin\stack.exe

- ps: Start-FileDownload https://github.com/lehins/cache-s3/releases/download/latest/cache-s3-latest-windows-x86_64.zip -FileName cache-s3.zip
- ps: 7z x cache-s3.zip cache-s3.exe
- ps: .\cache-s3 --prefix=$env:APPVEYOR_PROJECT_NAME
                 --git-branch=$env:APPVEYOR_REPO_BRANCH
                 --suffix=windows
                 --verbosity=debug
                 restore
                 stack --base-branch=master
- ps: .\cache-s3 --prefix=$env:APPVEYOR_PROJECT_NAME
                 --git-branch=$env:APPVEYOR_REPO_BRANCH
                 --suffix=windows
                 --verbosity=debug
                 restore
                 stack work --base-branch=master


test_script:
- cd "%WORK_DIR%"
- stack --verbosity warn setup --no-reinstall > nul
- stack install
    -j 2
    --no-terminal
    --work-dir %STACK_WORK%


after_test:
- ps: >-
    if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER ) {
      if ($env:APPVEYOR_REPO_BRANCH -eq "master" ) {
        stack exec -- cache-s3 --prefix=$env:APPVEYOR_PROJECT_NAME --git-branch=$env:APPVEYOR_REPO_BRANCH --suffix=windows -v debug save stack
      }
      stack exec -- cache-s3 --prefix=$env:APPVEYOR_PROJECT_NAME --git-branch=$env:APPVEYOR_REPO_BRANCH --suffix=windows -v debug save stack work
    }
# Make a release on every git tag
- ps: >-
    if ($env:APPVEYOR_REPO_TAG_NAME) {
      Start-FileDownload https://github.com/tfausak/github-release/releases/download/$env:GITHUB_RELEASE_VERSION/github-release-$env:GITHUB_RELEASE_VERSION-windows.zip -FileName github-release.zip
      7z x github-release.zip github-release.exe
      cp $env:APPDATA\local\bin\cache-s3.exe cache-s3.exe
      7z a cache-s3.zip cache-s3.exe
      .\github-release version
      .\github-release upload --token=$env:GITHUB_TOKEN --owner=lehins --repo=cache-s3 --file=cache-s3.zip --tag=$env:APPVEYOR_REPO_TAG_NAME --name=cache-s3-$env:APPVEYOR_REPO_TAG_NAME-windows_x64-86.zip
    }
notifications:
  - provider: Email
    to:
      - lehins@yandex.ru
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
