resolver: nightly-2017-12-08
packages:
- .
- location:
    git: https://github.com/lehins/tar-conduit
    commit: 7ffdb1bb85e9d45e49977e16ca31dee6bea3d6f3
  extra-dep: true
extra-deps:
- temporary-resourcet-0.1.0.0
- lz4-conduit-0.2
