resolver: lts-10.0
packages:
- .
- location:
    git: https://github.com/lehins/tar-conduit
    commit: 76129dd459de628d10565513b16d16647f1782a4
  extra-dep: true
extra-deps:
- amazonka-1.4.5
- amazonka-core-1.4.5
- amazonka-s3-1.4.5
- amazonka-s3-streaming-0.2.0.3
- conduit-extra-1.1.17
- temporary-resourcet-0.1.0.0
- lz4-conduit-0.2
