resolver: nightly-2017-12-08
packages:
- .
- location:
    git: https://github.com/lehins/tar-conduit
    commit: 76129dd459de628d10565513b16d16647f1782a4
  extra-dep: true
extra-deps:
- temporary-resourcet-0.1.0.0
- lz4-conduit-0.2
