resolver: lts-10.0
packages:
- .
- location:
    git: https://github.com/snoyberg/tar-conduit
    commit: ac58871a069a8d4a3746595e27f72d74a132d94b
  extra-dep: true
extra-deps:
- amazonka-1.4.5
- amazonka-core-1.4.5
- amazonka-s3-1.4.5
- amazonka-s3-streaming-0.2.0.3
- conduit-extra-1.1.17
- temporary-resourcet-0.1.0.0
- lz4-conduit-0.2
- directory-1.3.2.0
